// Code generated by protoc-gen-go. DO NOT EDIT.
// source: persistent_msgs.proto

package pvtdatastorage // import "deepchain/core/ledger/pvtdatastorage"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExpiryData struct {
	Map                  map[string]*Collections `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ExpiryData) Reset()         { *m = ExpiryData{} }
func (m *ExpiryData) String() string { return proto.CompactTextString(m) }
func (*ExpiryData) ProtoMessage()    {}
func (*ExpiryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_persistent_msgs_2693758ad38ef9f7, []int{0}
}
func (m *ExpiryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpiryData.Unmarshal(m, b)
}
func (m *ExpiryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpiryData.Marshal(b, m, deterministic)
}
func (dst *ExpiryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpiryData.Merge(dst, src)
}
func (m *ExpiryData) XXX_Size() int {
	return xxx_messageInfo_ExpiryData.Size(m)
}
func (m *ExpiryData) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpiryData.DiscardUnknown(m)
}

var xxx_messageInfo_ExpiryData proto.InternalMessageInfo

func (m *ExpiryData) GetMap() map[string]*Collections {
	if m != nil {
		return m.Map
	}
	return nil
}

type Collections struct {
	// for pvt data, there would be an
	// entry in TxNums
	Map map[string]*TxNums `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// for any number of missing pvt data of a collection,
	// there would be an entry in the map
	MissingDataMap       map[string]bool `protobuf:"bytes,2,rep,name=missingDataMap,proto3" json:"missingDataMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Collections) Reset()         { *m = Collections{} }
func (m *Collections) String() string { return proto.CompactTextString(m) }
func (*Collections) ProtoMessage()    {}
func (*Collections) Descriptor() ([]byte, []int) {
	return fileDescriptor_persistent_msgs_2693758ad38ef9f7, []int{1}
}
func (m *Collections) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collections.Unmarshal(m, b)
}
func (m *Collections) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collections.Marshal(b, m, deterministic)
}
func (dst *Collections) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collections.Merge(dst, src)
}
func (m *Collections) XXX_Size() int {
	return xxx_messageInfo_Collections.Size(m)
}
func (m *Collections) XXX_DiscardUnknown() {
	xxx_messageInfo_Collections.DiscardUnknown(m)
}

var xxx_messageInfo_Collections proto.InternalMessageInfo

func (m *Collections) GetMap() map[string]*TxNums {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *Collections) GetMissingDataMap() map[string]bool {
	if m != nil {
		return m.MissingDataMap
	}
	return nil
}

type TxNums struct {
	List                 []uint64 `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxNums) Reset()         { *m = TxNums{} }
func (m *TxNums) String() string { return proto.CompactTextString(m) }
func (*TxNums) ProtoMessage()    {}
func (*TxNums) Descriptor() ([]byte, []int) {
	return fileDescriptor_persistent_msgs_2693758ad38ef9f7, []int{2}
}
func (m *TxNums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxNums.Unmarshal(m, b)
}
func (m *TxNums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxNums.Marshal(b, m, deterministic)
}
func (dst *TxNums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxNums.Merge(dst, src)
}
func (m *TxNums) XXX_Size() int {
	return xxx_messageInfo_TxNums.Size(m)
}
func (m *TxNums) XXX_DiscardUnknown() {
	xxx_messageInfo_TxNums.DiscardUnknown(m)
}

var xxx_messageInfo_TxNums proto.InternalMessageInfo

func (m *TxNums) GetList() []uint64 {
	if m != nil {
		return m.List
	}
	return nil
}

type CollElgInfo struct {
	NsCollMap            map[string]*CollNames `protobuf:"bytes,1,rep,name=nsCollMap,proto3" json:"nsCollMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CollElgInfo) Reset()         { *m = CollElgInfo{} }
func (m *CollElgInfo) String() string { return proto.CompactTextString(m) }
func (*CollElgInfo) ProtoMessage()    {}
func (*CollElgInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_persistent_msgs_2693758ad38ef9f7, []int{3}
}
func (m *CollElgInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollElgInfo.Unmarshal(m, b)
}
func (m *CollElgInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollElgInfo.Marshal(b, m, deterministic)
}
func (dst *CollElgInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollElgInfo.Merge(dst, src)
}
func (m *CollElgInfo) XXX_Size() int {
	return xxx_messageInfo_CollElgInfo.Size(m)
}
func (m *CollElgInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CollElgInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CollElgInfo proto.InternalMessageInfo

func (m *CollElgInfo) GetNsCollMap() map[string]*CollNames {
	if m != nil {
		return m.NsCollMap
	}
	return nil
}

type CollNames struct {
	Entries              []string `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollNames) Reset()         { *m = CollNames{} }
func (m *CollNames) String() string { return proto.CompactTextString(m) }
func (*CollNames) ProtoMessage()    {}
func (*CollNames) Descriptor() ([]byte, []int) {
	return fileDescriptor_persistent_msgs_2693758ad38ef9f7, []int{4}
}
func (m *CollNames) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollNames.Unmarshal(m, b)
}
func (m *CollNames) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollNames.Marshal(b, m, deterministic)
}
func (dst *CollNames) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollNames.Merge(dst, src)
}
func (m *CollNames) XXX_Size() int {
	return xxx_messageInfo_CollNames.Size(m)
}
func (m *CollNames) XXX_DiscardUnknown() {
	xxx_messageInfo_CollNames.DiscardUnknown(m)
}

var xxx_messageInfo_CollNames proto.InternalMessageInfo

func (m *CollNames) GetEntries() []string {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*ExpiryData)(nil), "pvtdatastorage.ExpiryData")
	proto.RegisterMapType((map[string]*Collections)(nil), "pvtdatastorage.ExpiryData.MapEntry")
	proto.RegisterType((*Collections)(nil), "pvtdatastorage.Collections")
	proto.RegisterMapType((map[string]*TxNums)(nil), "pvtdatastorage.Collections.MapEntry")
	proto.RegisterMapType((map[string]bool)(nil), "pvtdatastorage.Collections.MissingDataMapEntry")
	proto.RegisterType((*TxNums)(nil), "pvtdatastorage.TxNums")
	proto.RegisterType((*CollElgInfo)(nil), "pvtdatastorage.CollElgInfo")
	proto.RegisterMapType((map[string]*CollNames)(nil), "pvtdatastorage.CollElgInfo.NsCollMapEntry")
	proto.RegisterType((*CollNames)(nil), "pvtdatastorage.CollNames")
}

func init() {
	proto.RegisterFile("persistent_msgs.proto", fileDescriptor_persistent_msgs_2693758ad38ef9f7)
}

var fileDescriptor_persistent_msgs_2693758ad38ef9f7 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0x69, 0xb7, 0x77, 0xef, 0x7a, 0x06, 0xe3, 0x25, 0xaf, 0x4a, 0xad, 0x5e, 0x8c, 0x39,
	0x65, 0x88, 0xb4, 0x38, 0x51, 0xc4, 0x3b, 0xff, 0x0c, 0xf4, 0x62, 0xbd, 0xa8, 0xc2, 0xc0, 0x1b,
	0x89, 0x5b, 0xac, 0xc1, 0x36, 0x0d, 0x49, 0x36, 0xb6, 0x6f, 0xe2, 0xc7, 0xd0, 0x6f, 0x28, 0x6d,
	0xdd, 0xd6, 0x8c, 0xb2, 0xbb, 0xf4, 0xe4, 0x39, 0xbf, 0xf3, 0x9c, 0x87, 0x06, 0xb6, 0x39, 0x11,
	0x92, 0x4a, 0x45, 0x98, 0x7a, 0x89, 0x65, 0x28, 0x5d, 0x2e, 0x12, 0x95, 0xa0, 0x26, 0x9f, 0xaa,
	0x31, 0x56, 0x58, 0xaa, 0x44, 0xe0, 0x90, 0xb4, 0x3f, 0x0d, 0x80, 0xfe, 0x8c, 0x53, 0x31, 0xbf,
	0xc3, 0x0a, 0xa3, 0x73, 0xa8, 0xc4, 0x98, 0xdb, 0x46, 0xab, 0xd2, 0x6d, 0xf4, 0x0e, 0x5c, 0x5d,
	0xec, 0xae, 0x84, 0xee, 0x00, 0xf3, 0x3e, 0x53, 0x62, 0x1e, 0xa4, 0x7a, 0xe7, 0x11, 0xea, 0x8b,
	0x02, 0xfa, 0x07, 0x95, 0x0f, 0x32, 0xb7, 0x8d, 0x96, 0xd1, 0xb5, 0x82, 0xf4, 0x88, 0x4e, 0xe1,
	0xcf, 0x14, 0x47, 0x13, 0x62, 0x9b, 0x2d, 0xa3, 0xdb, 0xe8, 0xed, 0xad, 0x63, 0x6f, 0x93, 0x28,
	0x22, 0x23, 0x45, 0x13, 0x26, 0x83, 0x5c, 0x79, 0x65, 0x5e, 0x1a, 0xed, 0x6f, 0x13, 0x1a, 0x85,
	0x2b, 0x74, 0x51, 0xf4, 0xd6, 0xd9, 0x00, 0xd1, 0xcd, 0xa1, 0x21, 0x34, 0x63, 0x2a, 0x25, 0x65,
	0x61, 0xea, 0x7c, 0x80, 0xb9, 0x6d, 0x66, 0x08, 0x6f, 0x23, 0x42, 0xeb, 0xc8, 0x69, 0x6b, 0x18,
	0xc7, 0xdf, 0xb8, 0xf5, 0x89, 0xbe, 0xf5, 0xce, 0xfa, 0xb4, 0xa7, 0x99, 0x3f, 0x89, 0x8b, 0x0b,
	0x3b, 0xd7, 0xf0, 0xbf, 0x64, 0x6c, 0x09, 0x7a, 0xab, 0x88, 0xae, 0x17, 0x33, 0xdb, 0x87, 0x5a,
	0xce, 0x45, 0x08, 0xaa, 0x11, 0x95, 0x2a, 0x8b, 0xab, 0x1a, 0x64, 0xe7, 0xf6, 0x97, 0x91, 0x27,
	0xda, 0x8f, 0xc2, 0x07, 0xf6, 0x96, 0xa0, 0x7b, 0xb0, 0x98, 0x4c, 0x0b, 0x83, 0x65, 0xae, 0xc7,
	0x65, 0xa1, 0xfc, 0xea, 0x5d, 0x7f, 0x21, 0xce, 0xf3, 0x58, 0x35, 0x3b, 0x43, 0x68, 0xea, 0x97,
	0x25, 0xae, 0x3d, 0x3d, 0x90, 0xdd, 0xb2, 0x49, 0x3e, 0x8e, 0x89, 0xf6, 0x13, 0x1c, 0x82, 0xb5,
	0xac, 0x23, 0x1b, 0xfe, 0x12, 0xa6, 0x04, 0x25, 0x32, 0x73, 0x6b, 0x05, 0x8b, 0xcf, 0x9b, 0xa3,
	0xe7, 0xce, 0x98, 0x10, 0x3e, 0x7a, 0xc7, 0x94, 0x79, 0xa3, 0x44, 0x10, 0x2f, 0x22, 0xe3, 0x90,
	0x08, 0x4f, 0x9f, 0xf1, 0x5a, 0xcb, 0x5e, 0xc1, 0xd9, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61,
	0xc5, 0x9f, 0x40, 0x1e, 0x03, 0x00, 0x00,
}
