// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msp/identities.proto

package msp // import "deepchain/protos/msp"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// This struct represents an Identity
// (with its MSP identifier) to be used
// to serialize it and deserialize it
type SerializedIdentity struct {
	// The identifier of the associated membership service provider
	Mspid string `protobuf:"bytes,1,opt,name=mspid,proto3" json:"mspid,omitempty"`
	// the Identity, serialized according to the rules of its MPS
	IdBytes              []byte   `protobuf:"bytes,2,opt,name=id_bytes,json=idBytes,proto3" json:"id_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerializedIdentity) Reset()         { *m = SerializedIdentity{} }
func (m *SerializedIdentity) String() string { return proto.CompactTextString(m) }
func (*SerializedIdentity) ProtoMessage()    {}
func (*SerializedIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_identities_e20a1b11b7b6c8d8, []int{0}
}
func (m *SerializedIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializedIdentity.Unmarshal(m, b)
}
func (m *SerializedIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializedIdentity.Marshal(b, m, deterministic)
}
func (dst *SerializedIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializedIdentity.Merge(dst, src)
}
func (m *SerializedIdentity) XXX_Size() int {
	return xxx_messageInfo_SerializedIdentity.Size(m)
}
func (m *SerializedIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializedIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_SerializedIdentity proto.InternalMessageInfo

func (m *SerializedIdentity) GetMspid() string {
	if m != nil {
		return m.Mspid
	}
	return ""
}

func (m *SerializedIdentity) GetIdBytes() []byte {
	if m != nil {
		return m.IdBytes
	}
	return nil
}

// This struct represents an Idemix Identity
// to be used to serialize it and deserialize it.
// The IdemixMSP will first serialize an idemix identity to bytes using
// this proto, and then uses these bytes as id_bytes in SerializedIdentity
type SerializedIdemixIdentity struct {
	// nym_x is the X-component of the pseudonym elliptic curve point.
	// It is a []byte representation of an amcl.BIG
	// The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
	NymX []byte `protobuf:"bytes,1,opt,name=nym_x,json=nymX,proto3" json:"nym_x,omitempty"`
	// nym_y is the Y-component of the pseudonym elliptic curve point.
	// It is a []byte representation of an amcl.BIG
	// The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
	NymY []byte `protobuf:"bytes,2,opt,name=nym_y,json=nymY,proto3" json:"nym_y,omitempty"`
	// ou contains the organizational unit of the idemix identity
	Ou []byte `protobuf:"bytes,3,opt,name=ou,proto3" json:"ou,omitempty"`
	// role contains the role of this identity (e.g., ADMIN or MEMBER)
	Role []byte `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	// proof contains the cryptographic evidence that this identity is valid
	Proof                []byte   `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerializedIdemixIdentity) Reset()         { *m = SerializedIdemixIdentity{} }
func (m *SerializedIdemixIdentity) String() string { return proto.CompactTextString(m) }
func (*SerializedIdemixIdentity) ProtoMessage()    {}
func (*SerializedIdemixIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_identities_e20a1b11b7b6c8d8, []int{1}
}
func (m *SerializedIdemixIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializedIdemixIdentity.Unmarshal(m, b)
}
func (m *SerializedIdemixIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializedIdemixIdentity.Marshal(b, m, deterministic)
}
func (dst *SerializedIdemixIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializedIdemixIdentity.Merge(dst, src)
}
func (m *SerializedIdemixIdentity) XXX_Size() int {
	return xxx_messageInfo_SerializedIdemixIdentity.Size(m)
}
func (m *SerializedIdemixIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializedIdemixIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_SerializedIdemixIdentity proto.InternalMessageInfo

func (m *SerializedIdemixIdentity) GetNymX() []byte {
	if m != nil {
		return m.NymX
	}
	return nil
}

func (m *SerializedIdemixIdentity) GetNymY() []byte {
	if m != nil {
		return m.NymY
	}
	return nil
}

func (m *SerializedIdemixIdentity) GetOu() []byte {
	if m != nil {
		return m.Ou
	}
	return nil
}

func (m *SerializedIdemixIdentity) GetRole() []byte {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *SerializedIdemixIdentity) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func init() {
	proto.RegisterType((*SerializedIdentity)(nil), "msp.SerializedIdentity")
	proto.RegisterType((*SerializedIdemixIdentity)(nil), "msp.SerializedIdemixIdentity")
}

func init() { proto.RegisterFile("msp/identities.proto", fileDescriptor_identities_e20a1b11b7b6c8d8) }

var fileDescriptor_identities_e20a1b11b7b6c8d8 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xbf, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x34, 0xe1, 0xc7, 0xa9, 0x62, 0x30, 0x19, 0xcc, 0x56, 0x3a, 0x75, 0x4a, 0x06,
	0x26, 0xd6, 0x4a, 0x0c, 0xac, 0x61, 0x01, 0x96, 0x2a, 0xa9, 0xaf, 0xed, 0x49, 0x71, 0x7c, 0xf2,
	0xa5, 0x52, 0xcc, 0xc0, 0xdf, 0x8e, 0x12, 0x03, 0x52, 0xb7, 0xf7, 0x3e, 0x3d, 0x7d, 0xba, 0x83,
	0xc2, 0x0a, 0x57, 0x64, 0xb0, 0x1f, 0x68, 0x20, 0x94, 0x92, 0xbd, 0x1b, 0x9c, 0x5a, 0x58, 0xe1,
	0xf5, 0x0b, 0xa8, 0x37, 0xf4, 0xd4, 0x74, 0xf4, 0x85, 0xe6, 0x35, 0x4e, 0x82, 0x2a, 0x20, 0xb7,
	0xc2, 0x64, 0x74, 0xb2, 0x4a, 0x36, 0xb7, 0x75, 0x2c, 0xea, 0x01, 0x6e, 0xc8, 0xec, 0xda, 0x30,
	0xa0, 0xe8, 0x74, 0x95, 0x6c, 0x96, 0xf5, 0x35, 0x99, 0xed, 0x54, 0xd7, 0xdf, 0xa0, 0x2f, 0x34,
	0x96, 0xc6, 0x7f, 0xd9, 0x3d, 0xe4, 0x7d, 0xb0, 0xbb, 0x71, 0x96, 0x2d, 0xeb, 0xac, 0x0f, 0xf6,
	0xfd, 0x0f, 0x86, 0x5f, 0xd1, 0x04, 0x3f, 0xd4, 0x1d, 0xa4, 0xee, 0xac, 0x17, 0x33, 0x49, 0xdd,
	0x59, 0x29, 0xc8, 0xbc, 0xeb, 0x50, 0x67, 0x71, 0x33, 0xe5, 0xe9, 0x34, 0xf6, 0xce, 0x1d, 0x74,
	0x3e, 0xc3, 0x58, 0xb6, 0xcf, 0xf0, 0xe8, 0xfc, 0xb1, 0x3c, 0x05, 0x46, 0xdf, 0xa1, 0x39, 0xa2,
	0x2f, 0x0f, 0x4d, 0xeb, 0x69, 0x1f, 0x7f, 0x95, 0xd2, 0x0a, 0x7f, 0x16, 0x06, 0x91, 0xf7, 0xa7,
	0x86, 0xfa, 0x2a, 0xd2, 0xca, 0x0a, 0xb7, 0x57, 0x73, 0x7e, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x27, 0x2b, 0x63, 0xdb, 0x25, 0x01, 0x00, 0x00,
}
