// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer/configuration.proto

package peer // import "deepchain/protos/peer"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AnchorPeers simply represents list of anchor peers which is used in ConfigurationItem
type AnchorPeers struct {
	AnchorPeers          []*AnchorPeer `protobuf:"bytes,1,rep,name=anchor_peers,json=anchorPeers,proto3" json:"anchor_peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AnchorPeers) Reset()         { *m = AnchorPeers{} }
func (m *AnchorPeers) String() string { return proto.CompactTextString(m) }
func (*AnchorPeers) ProtoMessage()    {}
func (*AnchorPeers) Descriptor() ([]byte, []int) {
	return fileDescriptor_configuration_8a1afcff7729f4d7, []int{0}
}
func (m *AnchorPeers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnchorPeers.Unmarshal(m, b)
}
func (m *AnchorPeers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnchorPeers.Marshal(b, m, deterministic)
}
func (dst *AnchorPeers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnchorPeers.Merge(dst, src)
}
func (m *AnchorPeers) XXX_Size() int {
	return xxx_messageInfo_AnchorPeers.Size(m)
}
func (m *AnchorPeers) XXX_DiscardUnknown() {
	xxx_messageInfo_AnchorPeers.DiscardUnknown(m)
}

var xxx_messageInfo_AnchorPeers proto.InternalMessageInfo

func (m *AnchorPeers) GetAnchorPeers() []*AnchorPeer {
	if m != nil {
		return m.AnchorPeers
	}
	return nil
}

// AnchorPeer message structure which provides information about anchor peer, it includes host name,
// port number and peer certificate.
type AnchorPeer struct {
	// DNS host name of the anchor peer
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// The port number
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnchorPeer) Reset()         { *m = AnchorPeer{} }
func (m *AnchorPeer) String() string { return proto.CompactTextString(m) }
func (*AnchorPeer) ProtoMessage()    {}
func (*AnchorPeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_configuration_8a1afcff7729f4d7, []int{1}
}
func (m *AnchorPeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnchorPeer.Unmarshal(m, b)
}
func (m *AnchorPeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnchorPeer.Marshal(b, m, deterministic)
}
func (dst *AnchorPeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnchorPeer.Merge(dst, src)
}
func (m *AnchorPeer) XXX_Size() int {
	return xxx_messageInfo_AnchorPeer.Size(m)
}
func (m *AnchorPeer) XXX_DiscardUnknown() {
	xxx_messageInfo_AnchorPeer.DiscardUnknown(m)
}

var xxx_messageInfo_AnchorPeer proto.InternalMessageInfo

func (m *AnchorPeer) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *AnchorPeer) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// APIResource represents an API resource in the peer whose ACL
// is determined by the policy_ref field
type APIResource struct {
	PolicyRef            string   `protobuf:"bytes,1,opt,name=policy_ref,json=policyRef,proto3" json:"policy_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIResource) Reset()         { *m = APIResource{} }
func (m *APIResource) String() string { return proto.CompactTextString(m) }
func (*APIResource) ProtoMessage()    {}
func (*APIResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_configuration_8a1afcff7729f4d7, []int{2}
}
func (m *APIResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIResource.Unmarshal(m, b)
}
func (m *APIResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIResource.Marshal(b, m, deterministic)
}
func (dst *APIResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIResource.Merge(dst, src)
}
func (m *APIResource) XXX_Size() int {
	return xxx_messageInfo_APIResource.Size(m)
}
func (m *APIResource) XXX_DiscardUnknown() {
	xxx_messageInfo_APIResource.DiscardUnknown(m)
}

var xxx_messageInfo_APIResource proto.InternalMessageInfo

func (m *APIResource) GetPolicyRef() string {
	if m != nil {
		return m.PolicyRef
	}
	return ""
}

// ACLs provides mappings for resources in a channel. APIResource encapsulates
// reference to a policy used to determine ACL for the resource
type ACLs struct {
	Acls                 map[string]*APIResource `protobuf:"bytes,1,rep,name=acls,proto3" json:"acls,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ACLs) Reset()         { *m = ACLs{} }
func (m *ACLs) String() string { return proto.CompactTextString(m) }
func (*ACLs) ProtoMessage()    {}
func (*ACLs) Descriptor() ([]byte, []int) {
	return fileDescriptor_configuration_8a1afcff7729f4d7, []int{3}
}
func (m *ACLs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACLs.Unmarshal(m, b)
}
func (m *ACLs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACLs.Marshal(b, m, deterministic)
}
func (dst *ACLs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACLs.Merge(dst, src)
}
func (m *ACLs) XXX_Size() int {
	return xxx_messageInfo_ACLs.Size(m)
}
func (m *ACLs) XXX_DiscardUnknown() {
	xxx_messageInfo_ACLs.DiscardUnknown(m)
}

var xxx_messageInfo_ACLs proto.InternalMessageInfo

func (m *ACLs) GetAcls() map[string]*APIResource {
	if m != nil {
		return m.Acls
	}
	return nil
}

func init() {
	proto.RegisterType((*AnchorPeers)(nil), "protos.AnchorPeers")
	proto.RegisterType((*AnchorPeer)(nil), "protos.AnchorPeer")
	proto.RegisterType((*APIResource)(nil), "protos.APIResource")
	proto.RegisterType((*ACLs)(nil), "protos.ACLs")
	proto.RegisterMapType((map[string]*APIResource)(nil), "protos.ACLs.AclsEntry")
}

func init() {
	proto.RegisterFile("peer/configuration.proto", fileDescriptor_configuration_8a1afcff7729f4d7)
}

var fileDescriptor_configuration_8a1afcff7729f4d7 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xcd, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xd9, 0x7e, 0x08, 0x9d, 0x78, 0x90, 0x15, 0x25, 0x08, 0x42, 0xc9, 0xa9, 0x8a, 0x24,
	0x50, 0x15, 0x44, 0x4f, 0xb1, 0x7a, 0x10, 0x72, 0x28, 0x7b, 0xf4, 0x52, 0xb6, 0xdb, 0xc9, 0x07,
	0x86, 0xec, 0x32, 0x9b, 0x08, 0xb9, 0xf9, 0xa7, 0x4b, 0x36, 0x6d, 0x72, 0xda, 0xb7, 0x6f, 0xde,
	0x6f, 0x78, 0x0c, 0xf8, 0x06, 0x91, 0x22, 0xa5, 0xab, 0xb4, 0xc8, 0x1a, 0x92, 0x75, 0xa1, 0xab,
	0xd0, 0x90, 0xae, 0x35, 0x3f, 0x73, 0x8f, 0x0d, 0x3e, 0xc0, 0x8b, 0x2b, 0x95, 0x6b, 0xda, 0x22,
	0x92, 0xe5, 0xcf, 0x70, 0x2e, 0xdd, 0x77, 0xd7, 0x91, 0xd6, 0x67, 0xcb, 0xe9, 0xca, 0x5b, 0xf3,
	0x1e, 0xb2, 0xe1, 0x18, 0x15, 0x9e, 0x1c, 0xb1, 0xe0, 0x09, 0x60, 0x1c, 0x71, 0x0e, 0xb3, 0x5c,
	0xdb, 0xda, 0x67, 0x4b, 0xb6, 0x5a, 0x08, 0xa7, 0x3b, 0xcf, 0x68, 0xaa, 0xfd, 0xc9, 0x92, 0xad,
	0xe6, 0xc2, 0xe9, 0xe0, 0x01, 0xbc, 0x78, 0xfb, 0x25, 0xd0, 0xea, 0x86, 0x14, 0xf2, 0x5b, 0x00,
	0xa3, 0xcb, 0x42, 0xb5, 0x3b, 0xc2, 0xf4, 0x08, 0x2f, 0x7a, 0x47, 0x60, 0x1a, 0xfc, 0x31, 0x98,
	0xc5, 0x9b, 0xc4, 0xf2, 0x7b, 0x98, 0x49, 0x55, 0x9e, 0xba, 0x5d, 0x0f, 0xdd, 0x36, 0x89, 0x0d,
	0x63, 0x55, 0xda, 0xcf, 0xaa, 0xa6, 0x56, 0xb8, 0xcc, 0x4d, 0x02, 0x8b, 0xc1, 0xe2, 0x17, 0x30,
	0xfd, 0xc1, 0xf6, 0xb8, 0xb9, 0x93, 0xfc, 0x0e, 0xe6, 0xbf, 0xb2, 0x6c, 0xd0, 0xd5, 0xf2, 0xd6,
	0x97, 0xc3, 0xae, 0xb1, 0x96, 0xe8, 0x13, 0xaf, 0x93, 0x17, 0xf6, 0xfe, 0x06, 0x81, 0xa6, 0x2c,
	0xcc, 0x5b, 0x83, 0x54, 0xe2, 0x21, 0x43, 0x0a, 0x53, 0xb9, 0xa7, 0x42, 0x9d, 0xb8, 0xee, 0x68,
	0xdf, 0x57, 0x07, 0x44, 0xa3, 0x72, 0x59, 0x54, 0x51, 0x6f, 0x47, 0x9d, 0xbd, 0xef, 0x2f, 0xfe,
	0xf8, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x38, 0x06, 0x0e, 0x25, 0x94, 0x01, 0x00, 0x00,
}
