// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer/peer.proto

package peer // import "deepchain/protos/peer"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerID struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerID) Reset()         { *m = PeerID{} }
func (m *PeerID) String() string { return proto.CompactTextString(m) }
func (*PeerID) ProtoMessage()    {}
func (*PeerID) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_ba92724ad8e8a8ac, []int{0}
}
func (m *PeerID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerID.Unmarshal(m, b)
}
func (m *PeerID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerID.Marshal(b, m, deterministic)
}
func (dst *PeerID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerID.Merge(dst, src)
}
func (m *PeerID) XXX_Size() int {
	return xxx_messageInfo_PeerID.Size(m)
}
func (m *PeerID) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerID.DiscardUnknown(m)
}

var xxx_messageInfo_PeerID proto.InternalMessageInfo

func (m *PeerID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PeerEndpoint struct {
	Id                   *PeerID  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerEndpoint) Reset()         { *m = PeerEndpoint{} }
func (m *PeerEndpoint) String() string { return proto.CompactTextString(m) }
func (*PeerEndpoint) ProtoMessage()    {}
func (*PeerEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_ba92724ad8e8a8ac, []int{1}
}
func (m *PeerEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerEndpoint.Unmarshal(m, b)
}
func (m *PeerEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerEndpoint.Marshal(b, m, deterministic)
}
func (dst *PeerEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerEndpoint.Merge(dst, src)
}
func (m *PeerEndpoint) XXX_Size() int {
	return xxx_messageInfo_PeerEndpoint.Size(m)
}
func (m *PeerEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_PeerEndpoint proto.InternalMessageInfo

func (m *PeerEndpoint) GetId() *PeerID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PeerEndpoint) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*PeerID)(nil), "protos.PeerID")
	proto.RegisterType((*PeerEndpoint)(nil), "protos.PeerEndpoint")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EndorserClient is the client API for Endorser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EndorserClient interface {
	ProcessProposal(ctx context.Context, in *SignedProposal, opts ...grpc.CallOption) (*ProposalResponse, error)
}

type endorserClient struct {
	cc *grpc.ClientConn
}

func NewEndorserClient(cc *grpc.ClientConn) EndorserClient {
	return &endorserClient{cc}
}

func (c *endorserClient) ProcessProposal(ctx context.Context, in *SignedProposal, opts ...grpc.CallOption) (*ProposalResponse, error) {
	out := new(ProposalResponse)
	err := c.cc.Invoke(ctx, "/protos.Endorser/ProcessProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndorserServer is the server API for Endorser service.
type EndorserServer interface {
	ProcessProposal(context.Context, *SignedProposal) (*ProposalResponse, error)
}

func RegisterEndorserServer(s *grpc.Server, srv EndorserServer) {
	s.RegisterService(&_Endorser_serviceDesc, srv)
}

func _Endorser_ProcessProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndorserServer).ProcessProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Endorser/ProcessProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndorserServer).ProcessProposal(ctx, req.(*SignedProposal))
	}
	return interceptor(ctx, in, info, handler)
}

var _Endorser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Endorser",
	HandlerType: (*EndorserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessProposal",
			Handler:    _Endorser_ProcessProposal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "peer/peer.proto",
}

func init() { proto.RegisterFile("peer/peer.proto", fileDescriptor_peer_ba92724ad8e8a8ac) }

var fileDescriptor_peer_ba92724ad8e8a8ac = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xdd, 0x22, 0xab, 0x8e, 0xe2, 0x42, 0x44, 0x29, 0x65, 0x11, 0xe9, 0xc9, 0x53, 0x17,
	0xd6, 0xa3, 0x37, 0xb1, 0xa0, 0xb7, 0x5a, 0x6f, 0x5e, 0x24, 0xdb, 0x19, 0xbb, 0x81, 0x35, 0x13,
	0x66, 0x7a, 0xf1, 0xdb, 0x4b, 0x93, 0x56, 0xf0, 0x92, 0x3f, 0xef, 0x97, 0x79, 0x99, 0x79, 0xb0,
	0x0a, 0x44, 0xb2, 0x19, 0x97, 0x2a, 0x08, 0x0f, 0x6c, 0x96, 0x71, 0xd3, 0xe2, 0x2a, 0x01, 0xe1,
	0xc0, 0x6a, 0x0f, 0x09, 0x16, 0xeb, 0x7f, 0xe2, 0xa7, 0x90, 0x06, 0xf6, 0x4a, 0x89, 0x96, 0x6b,
	0x58, 0x36, 0x44, 0xf2, 0xfa, 0x6c, 0x0c, 0x1c, 0x7b, 0xfb, 0x4d, 0xf9, 0xe2, 0x6e, 0x71, 0x7f,
	0xd6, 0xc6, 0x73, 0xf9, 0x02, 0x17, 0x23, 0xad, 0x3d, 0x06, 0x76, 0x7e, 0x30, 0xb7, 0x90, 0x39,
	0x8c, 0x2f, 0xce, 0xb7, 0x97, 0xc9, 0x41, 0xab, 0x54, 0xdf, 0x66, 0x0e, 0x4d, 0x0e, 0x27, 0x16,
	0x51, 0x48, 0x35, 0xcf, 0xa2, 0xcd, 0x7c, 0xdd, 0xbe, 0xc1, 0x69, 0xed, 0x91, 0x45, 0x49, 0x4c,
	0x0d, 0xab, 0x46, 0xb8, 0x23, 0xd5, 0x66, 0xea, 0xca, 0xdc, 0xcc, 0x66, 0xef, 0xae, 0xf7, 0x84,
	0xb3, 0x5e, 0xe4, 0x7f, 0x9f, 0x4c, 0x4a, 0x3b, 0xb5, 0x5f, 0x1e, 0x3d, 0x3d, 0x42, 0xc9, 0xd2,
	0x57, 0xfb, 0x9f, 0x40, 0x72, 0x20, 0xec, 0x49, 0xaa, 0x2f, 0xbb, 0x13, 0xd7, 0xcd, 0x35, 0xe3,
	0xe0, 0x1f, 0xd7, 0x48, 0x14, 0xba, 0xbd, 0x75, 0x7e, 0x93, 0xe4, 0x18, 0xdc, 0x2e, 0x45, 0xf6,
	0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x71, 0x59, 0x5b, 0xd2, 0x4c, 0x01, 0x00, 0x00,
}
