// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer/query.proto

package peer // import "deepchain/protos/peer"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ChaincodeQueryResponse returns information about each chaincode that pertains
// to a query in lscc.go, such as GetChaincodes (returns all chaincodes
// instantiated on a channel), and GetInstalledChaincodes (returns all chaincodes
// installed on a peer)
type ChaincodeQueryResponse struct {
	Chaincodes           []*ChaincodeInfo `protobuf:"bytes,1,rep,name=chaincodes,proto3" json:"chaincodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ChaincodeQueryResponse) Reset()         { *m = ChaincodeQueryResponse{} }
func (m *ChaincodeQueryResponse) String() string { return proto.CompactTextString(m) }
func (*ChaincodeQueryResponse) ProtoMessage()    {}
func (*ChaincodeQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_5ba57186172f4b12, []int{0}
}
func (m *ChaincodeQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeQueryResponse.Unmarshal(m, b)
}
func (m *ChaincodeQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeQueryResponse.Marshal(b, m, deterministic)
}
func (dst *ChaincodeQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeQueryResponse.Merge(dst, src)
}
func (m *ChaincodeQueryResponse) XXX_Size() int {
	return xxx_messageInfo_ChaincodeQueryResponse.Size(m)
}
func (m *ChaincodeQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeQueryResponse proto.InternalMessageInfo

func (m *ChaincodeQueryResponse) GetChaincodes() []*ChaincodeInfo {
	if m != nil {
		return m.Chaincodes
	}
	return nil
}

// ChaincodeInfo contains general information about an installed/instantiated
// chaincode
type ChaincodeInfo struct {
	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// the path as specified by the install/instantiate transaction
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// the chaincode function upon instantiation and its arguments. This will be
	// blank if the query is returning information about installed chaincodes.
	Input string `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	// the name of the ESCC for this chaincode. This will be
	// blank if the query is returning information about installed chaincodes.
	Escc string `protobuf:"bytes,5,opt,name=escc,proto3" json:"escc,omitempty"`
	// the name of the VSCC for this chaincode. This will be
	// blank if the query is returning information about installed chaincodes.
	Vscc string `protobuf:"bytes,6,opt,name=vscc,proto3" json:"vscc,omitempty"`
	// the chaincode unique id.
	// computed as: H(
	//                H(name || version) ||
	//                H(CodePackage)
	//              )
	Id                   []byte   `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChaincodeInfo) Reset()         { *m = ChaincodeInfo{} }
func (m *ChaincodeInfo) String() string { return proto.CompactTextString(m) }
func (*ChaincodeInfo) ProtoMessage()    {}
func (*ChaincodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_5ba57186172f4b12, []int{1}
}
func (m *ChaincodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeInfo.Unmarshal(m, b)
}
func (m *ChaincodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeInfo.Marshal(b, m, deterministic)
}
func (dst *ChaincodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeInfo.Merge(dst, src)
}
func (m *ChaincodeInfo) XXX_Size() int {
	return xxx_messageInfo_ChaincodeInfo.Size(m)
}
func (m *ChaincodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeInfo proto.InternalMessageInfo

func (m *ChaincodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChaincodeInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ChaincodeInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ChaincodeInfo) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *ChaincodeInfo) GetEscc() string {
	if m != nil {
		return m.Escc
	}
	return ""
}

func (m *ChaincodeInfo) GetVscc() string {
	if m != nil {
		return m.Vscc
	}
	return ""
}

func (m *ChaincodeInfo) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

// ChannelQueryResponse returns information about each channel that pertains
// to a query in lscc.go, such as GetChannels (returns all channels for a
// given peer)
type ChannelQueryResponse struct {
	Channels             []*ChannelInfo `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ChannelQueryResponse) Reset()         { *m = ChannelQueryResponse{} }
func (m *ChannelQueryResponse) String() string { return proto.CompactTextString(m) }
func (*ChannelQueryResponse) ProtoMessage()    {}
func (*ChannelQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_5ba57186172f4b12, []int{2}
}
func (m *ChannelQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelQueryResponse.Unmarshal(m, b)
}
func (m *ChannelQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelQueryResponse.Marshal(b, m, deterministic)
}
func (dst *ChannelQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelQueryResponse.Merge(dst, src)
}
func (m *ChannelQueryResponse) XXX_Size() int {
	return xxx_messageInfo_ChannelQueryResponse.Size(m)
}
func (m *ChannelQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelQueryResponse proto.InternalMessageInfo

func (m *ChannelQueryResponse) GetChannels() []*ChannelInfo {
	if m != nil {
		return m.Channels
	}
	return nil
}

// ChannelInfo contains general information about channels
type ChannelInfo struct {
	ChannelId            string   `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelInfo) Reset()         { *m = ChannelInfo{} }
func (m *ChannelInfo) String() string { return proto.CompactTextString(m) }
func (*ChannelInfo) ProtoMessage()    {}
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_5ba57186172f4b12, []int{3}
}
func (m *ChannelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInfo.Unmarshal(m, b)
}
func (m *ChannelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInfo.Marshal(b, m, deterministic)
}
func (dst *ChannelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInfo.Merge(dst, src)
}
func (m *ChannelInfo) XXX_Size() int {
	return xxx_messageInfo_ChannelInfo.Size(m)
}
func (m *ChannelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInfo proto.InternalMessageInfo

func (m *ChannelInfo) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func init() {
	proto.RegisterType((*ChaincodeQueryResponse)(nil), "protos.ChaincodeQueryResponse")
	proto.RegisterType((*ChaincodeInfo)(nil), "protos.ChaincodeInfo")
	proto.RegisterType((*ChannelQueryResponse)(nil), "protos.ChannelQueryResponse")
	proto.RegisterType((*ChannelInfo)(nil), "protos.ChannelInfo")
}

func init() { proto.RegisterFile("peer/query.proto", fileDescriptor_query_5ba57186172f4b12) }

var fileDescriptor_query_5ba57186172f4b12 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xbf, 0x6b, 0xfb, 0x30,
	0x10, 0xc5, 0x71, 0x7e, 0x7e, 0x73, 0xf9, 0xb6, 0x14, 0x35, 0x29, 0x5a, 0x0a, 0xc1, 0x93, 0x87,
	0x62, 0x43, 0x4b, 0xa7, 0x6e, 0xcd, 0x50, 0x32, 0x95, 0x7a, 0xec, 0x52, 0x1c, 0xe9, 0x12, 0x0b,
	0x52, 0x49, 0x95, 0x9c, 0x40, 0xfe, 0x9a, 0xfe, 0xab, 0xe5, 0xa4, 0x38, 0x38, 0x93, 0xdf, 0x7d,
	0xde, 0x13, 0xe6, 0xdd, 0xc1, 0x8d, 0x45, 0x74, 0xc5, 0xcf, 0x1e, 0xdd, 0x31, 0xb7, 0xce, 0x34,
	0x86, 0x8d, 0xc2, 0xc7, 0xa7, 0xef, 0x70, 0xb7, 0xac, 0x2b, 0xa5, 0x85, 0x91, 0xf8, 0x41, 0x7e,
	0x89, 0xde, 0x1a, 0xed, 0x91, 0x3d, 0x03, 0x88, 0xd6, 0xf1, 0x3c, 0x59, 0xf4, 0xb3, 0xe9, 0xe3,
	0x3c, 0xbe, 0xf6, 0xf9, 0xf9, 0xcd, 0x4a, 0x6f, 0x4c, 0xd9, 0x09, 0xa6, 0xbf, 0x09, 0x5c, 0x5d,
	0xb8, 0x8c, 0xc1, 0x40, 0x57, 0xdf, 0xc8, 0x93, 0x45, 0x92, 0x4d, 0xca, 0xa0, 0x19, 0x87, 0xf1,
	0x01, 0x9d, 0x57, 0x46, 0xf3, 0x5e, 0xc0, 0xed, 0x48, 0x69, 0x5b, 0x35, 0x35, 0xef, 0xc7, 0x34,
	0x69, 0x36, 0x83, 0xa1, 0xd2, 0x76, 0xdf, 0xf0, 0x41, 0x80, 0x71, 0xa0, 0x24, 0x7a, 0x21, 0xf8,
	0x30, 0x26, 0x49, 0x13, 0x3b, 0x10, 0x1b, 0x45, 0x46, 0x9a, 0x5d, 0x43, 0x4f, 0x49, 0x3e, 0x5e,
	0x24, 0xd9, 0xff, 0xb2, 0xa7, 0x64, 0xfa, 0x06, 0xb3, 0x65, 0x5d, 0x69, 0x8d, 0xbb, 0xcb, 0xc2,
	0x05, 0xfc, 0x13, 0x91, 0xb7, 0x75, 0x6f, 0x3b, 0x75, 0x89, 0x87, 0xb2, 0xe7, 0x50, 0xfa, 0x00,
	0xd3, 0x8e, 0xc1, 0xee, 0xc3, 0xc2, 0x68, 0xfc, 0x52, 0xf2, 0xd4, 0x76, 0x72, 0x22, 0x2b, 0xf9,
	0xfa, 0x02, 0xa9, 0x71, 0xdb, 0xbc, 0x3e, 0x5a, 0x74, 0x3b, 0x94, 0x5b, 0x74, 0xf9, 0xa6, 0x5a,
	0x3b, 0x25, 0xda, 0x9f, 0xd0, 0x8d, 0x3e, 0xe7, 0x12, 0xd1, 0x86, 0x75, 0x16, 0x11, 0x17, 0x84,
	0xd7, 0xf1, 0x5c, 0x4f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x61, 0x01, 0x34, 0x63, 0xc9, 0x01,
	0x00, 0x00,
}
