// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger/rwset/rwset.proto

package rwset // import "deepchain/protos/ledger/rwset"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxReadWriteSet_DataModel int32

const (
	TxReadWriteSet_KV TxReadWriteSet_DataModel = 0
)

var TxReadWriteSet_DataModel_name = map[int32]string{
	0: "KV",
}
var TxReadWriteSet_DataModel_value = map[string]int32{
	"KV": 0,
}

func (x TxReadWriteSet_DataModel) String() string {
	return proto.EnumName(TxReadWriteSet_DataModel_name, int32(x))
}
func (TxReadWriteSet_DataModel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_rwset_b932e8a3ac407f55, []int{0, 0}
}

// TxReadWriteSet encapsulates a read-write set for a transaction
// DataModel specifies the enum value of the data model
// ns_rwset field specifies a list of chaincode specific read-write set (one for each chaincode)
type TxReadWriteSet struct {
	DataModel            TxReadWriteSet_DataModel `protobuf:"varint,1,opt,name=data_model,json=dataModel,proto3,enum=rwset.TxReadWriteSet_DataModel" json:"data_model,omitempty"`
	NsRwset              []*NsReadWriteSet        `protobuf:"bytes,2,rep,name=ns_rwset,json=nsRwset,proto3" json:"ns_rwset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *TxReadWriteSet) Reset()         { *m = TxReadWriteSet{} }
func (m *TxReadWriteSet) String() string { return proto.CompactTextString(m) }
func (*TxReadWriteSet) ProtoMessage()    {}
func (*TxReadWriteSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_rwset_b932e8a3ac407f55, []int{0}
}
func (m *TxReadWriteSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxReadWriteSet.Unmarshal(m, b)
}
func (m *TxReadWriteSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxReadWriteSet.Marshal(b, m, deterministic)
}
func (dst *TxReadWriteSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxReadWriteSet.Merge(dst, src)
}
func (m *TxReadWriteSet) XXX_Size() int {
	return xxx_messageInfo_TxReadWriteSet.Size(m)
}
func (m *TxReadWriteSet) XXX_DiscardUnknown() {
	xxx_messageInfo_TxReadWriteSet.DiscardUnknown(m)
}

var xxx_messageInfo_TxReadWriteSet proto.InternalMessageInfo

func (m *TxReadWriteSet) GetDataModel() TxReadWriteSet_DataModel {
	if m != nil {
		return m.DataModel
	}
	return TxReadWriteSet_KV
}

func (m *TxReadWriteSet) GetNsRwset() []*NsReadWriteSet {
	if m != nil {
		return m.NsRwset
	}
	return nil
}

// NsReadWriteSet encapsulates the read-write set for a chaincode
type NsReadWriteSet struct {
	Namespace             string                          `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Rwset                 []byte                          `protobuf:"bytes,2,opt,name=rwset,proto3" json:"rwset,omitempty"`
	CollectionHashedRwset []*CollectionHashedReadWriteSet `protobuf:"bytes,3,rep,name=collection_hashed_rwset,json=collectionHashedRwset,proto3" json:"collection_hashed_rwset,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                        `json:"-"`
	XXX_unrecognized      []byte                          `json:"-"`
	XXX_sizecache         int32                           `json:"-"`
}

func (m *NsReadWriteSet) Reset()         { *m = NsReadWriteSet{} }
func (m *NsReadWriteSet) String() string { return proto.CompactTextString(m) }
func (*NsReadWriteSet) ProtoMessage()    {}
func (*NsReadWriteSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_rwset_b932e8a3ac407f55, []int{1}
}
func (m *NsReadWriteSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NsReadWriteSet.Unmarshal(m, b)
}
func (m *NsReadWriteSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NsReadWriteSet.Marshal(b, m, deterministic)
}
func (dst *NsReadWriteSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NsReadWriteSet.Merge(dst, src)
}
func (m *NsReadWriteSet) XXX_Size() int {
	return xxx_messageInfo_NsReadWriteSet.Size(m)
}
func (m *NsReadWriteSet) XXX_DiscardUnknown() {
	xxx_messageInfo_NsReadWriteSet.DiscardUnknown(m)
}

var xxx_messageInfo_NsReadWriteSet proto.InternalMessageInfo

func (m *NsReadWriteSet) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *NsReadWriteSet) GetRwset() []byte {
	if m != nil {
		return m.Rwset
	}
	return nil
}

func (m *NsReadWriteSet) GetCollectionHashedRwset() []*CollectionHashedReadWriteSet {
	if m != nil {
		return m.CollectionHashedRwset
	}
	return nil
}

// CollectionHashedReadWriteSet encapsulate the hashed representation for the private read-write set for a collection
type CollectionHashedReadWriteSet struct {
	CollectionName       string   `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	HashedRwset          []byte   `protobuf:"bytes,2,opt,name=hashed_rwset,json=hashedRwset,proto3" json:"hashed_rwset,omitempty"`
	PvtRwsetHash         []byte   `protobuf:"bytes,3,opt,name=pvt_rwset_hash,json=pvtRwsetHash,proto3" json:"pvt_rwset_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionHashedReadWriteSet) Reset()         { *m = CollectionHashedReadWriteSet{} }
func (m *CollectionHashedReadWriteSet) String() string { return proto.CompactTextString(m) }
func (*CollectionHashedReadWriteSet) ProtoMessage()    {}
func (*CollectionHashedReadWriteSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_rwset_b932e8a3ac407f55, []int{2}
}
func (m *CollectionHashedReadWriteSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionHashedReadWriteSet.Unmarshal(m, b)
}
func (m *CollectionHashedReadWriteSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionHashedReadWriteSet.Marshal(b, m, deterministic)
}
func (dst *CollectionHashedReadWriteSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionHashedReadWriteSet.Merge(dst, src)
}
func (m *CollectionHashedReadWriteSet) XXX_Size() int {
	return xxx_messageInfo_CollectionHashedReadWriteSet.Size(m)
}
func (m *CollectionHashedReadWriteSet) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionHashedReadWriteSet.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionHashedReadWriteSet proto.InternalMessageInfo

func (m *CollectionHashedReadWriteSet) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CollectionHashedReadWriteSet) GetHashedRwset() []byte {
	if m != nil {
		return m.HashedRwset
	}
	return nil
}

func (m *CollectionHashedReadWriteSet) GetPvtRwsetHash() []byte {
	if m != nil {
		return m.PvtRwsetHash
	}
	return nil
}

// TxPvtReadWriteSet encapsulate the private read-write set for a transaction
type TxPvtReadWriteSet struct {
	DataModel            TxReadWriteSet_DataModel `protobuf:"varint,1,opt,name=data_model,json=dataModel,proto3,enum=rwset.TxReadWriteSet_DataModel" json:"data_model,omitempty"`
	NsPvtRwset           []*NsPvtReadWriteSet     `protobuf:"bytes,2,rep,name=ns_pvt_rwset,json=nsPvtRwset,proto3" json:"ns_pvt_rwset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *TxPvtReadWriteSet) Reset()         { *m = TxPvtReadWriteSet{} }
func (m *TxPvtReadWriteSet) String() string { return proto.CompactTextString(m) }
func (*TxPvtReadWriteSet) ProtoMessage()    {}
func (*TxPvtReadWriteSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_rwset_b932e8a3ac407f55, []int{3}
}
func (m *TxPvtReadWriteSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxPvtReadWriteSet.Unmarshal(m, b)
}
func (m *TxPvtReadWriteSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxPvtReadWriteSet.Marshal(b, m, deterministic)
}
func (dst *TxPvtReadWriteSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxPvtReadWriteSet.Merge(dst, src)
}
func (m *TxPvtReadWriteSet) XXX_Size() int {
	return xxx_messageInfo_TxPvtReadWriteSet.Size(m)
}
func (m *TxPvtReadWriteSet) XXX_DiscardUnknown() {
	xxx_messageInfo_TxPvtReadWriteSet.DiscardUnknown(m)
}

var xxx_messageInfo_TxPvtReadWriteSet proto.InternalMessageInfo

func (m *TxPvtReadWriteSet) GetDataModel() TxReadWriteSet_DataModel {
	if m != nil {
		return m.DataModel
	}
	return TxReadWriteSet_KV
}

func (m *TxPvtReadWriteSet) GetNsPvtRwset() []*NsPvtReadWriteSet {
	if m != nil {
		return m.NsPvtRwset
	}
	return nil
}

// NsPvtReadWriteSet encapsulates the private read-write set for a chaincode
type NsPvtReadWriteSet struct {
	Namespace            string                       `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CollectionPvtRwset   []*CollectionPvtReadWriteSet `protobuf:"bytes,2,rep,name=collection_pvt_rwset,json=collectionPvtRwset,proto3" json:"collection_pvt_rwset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *NsPvtReadWriteSet) Reset()         { *m = NsPvtReadWriteSet{} }
func (m *NsPvtReadWriteSet) String() string { return proto.CompactTextString(m) }
func (*NsPvtReadWriteSet) ProtoMessage()    {}
func (*NsPvtReadWriteSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_rwset_b932e8a3ac407f55, []int{4}
}
func (m *NsPvtReadWriteSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NsPvtReadWriteSet.Unmarshal(m, b)
}
func (m *NsPvtReadWriteSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NsPvtReadWriteSet.Marshal(b, m, deterministic)
}
func (dst *NsPvtReadWriteSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NsPvtReadWriteSet.Merge(dst, src)
}
func (m *NsPvtReadWriteSet) XXX_Size() int {
	return xxx_messageInfo_NsPvtReadWriteSet.Size(m)
}
func (m *NsPvtReadWriteSet) XXX_DiscardUnknown() {
	xxx_messageInfo_NsPvtReadWriteSet.DiscardUnknown(m)
}

var xxx_messageInfo_NsPvtReadWriteSet proto.InternalMessageInfo

func (m *NsPvtReadWriteSet) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *NsPvtReadWriteSet) GetCollectionPvtRwset() []*CollectionPvtReadWriteSet {
	if m != nil {
		return m.CollectionPvtRwset
	}
	return nil
}

// CollectionPvtReadWriteSet encapsulates the private read-write set for a collection
type CollectionPvtReadWriteSet struct {
	CollectionName       string   `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Rwset                []byte   `protobuf:"bytes,2,opt,name=rwset,proto3" json:"rwset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionPvtReadWriteSet) Reset()         { *m = CollectionPvtReadWriteSet{} }
func (m *CollectionPvtReadWriteSet) String() string { return proto.CompactTextString(m) }
func (*CollectionPvtReadWriteSet) ProtoMessage()    {}
func (*CollectionPvtReadWriteSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_rwset_b932e8a3ac407f55, []int{5}
}
func (m *CollectionPvtReadWriteSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionPvtReadWriteSet.Unmarshal(m, b)
}
func (m *CollectionPvtReadWriteSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionPvtReadWriteSet.Marshal(b, m, deterministic)
}
func (dst *CollectionPvtReadWriteSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionPvtReadWriteSet.Merge(dst, src)
}
func (m *CollectionPvtReadWriteSet) XXX_Size() int {
	return xxx_messageInfo_CollectionPvtReadWriteSet.Size(m)
}
func (m *CollectionPvtReadWriteSet) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionPvtReadWriteSet.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionPvtReadWriteSet proto.InternalMessageInfo

func (m *CollectionPvtReadWriteSet) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CollectionPvtReadWriteSet) GetRwset() []byte {
	if m != nil {
		return m.Rwset
	}
	return nil
}

func init() {
	proto.RegisterType((*TxReadWriteSet)(nil), "rwset.TxReadWriteSet")
	proto.RegisterType((*NsReadWriteSet)(nil), "rwset.NsReadWriteSet")
	proto.RegisterType((*CollectionHashedReadWriteSet)(nil), "rwset.CollectionHashedReadWriteSet")
	proto.RegisterType((*TxPvtReadWriteSet)(nil), "rwset.TxPvtReadWriteSet")
	proto.RegisterType((*NsPvtReadWriteSet)(nil), "rwset.NsPvtReadWriteSet")
	proto.RegisterType((*CollectionPvtReadWriteSet)(nil), "rwset.CollectionPvtReadWriteSet")
	proto.RegisterEnum("rwset.TxReadWriteSet_DataModel", TxReadWriteSet_DataModel_name, TxReadWriteSet_DataModel_value)
}

func init() { proto.RegisterFile("ledger/rwset/rwset.proto", fileDescriptor_rwset_b932e8a3ac407f55) }

var fileDescriptor_rwset_b932e8a3ac407f55 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4f, 0x6f, 0xda, 0x30,
	0x18, 0xc6, 0x67, 0x10, 0x6c, 0x79, 0x89, 0xb2, 0xe1, 0x81, 0x96, 0x49, 0x4c, 0x63, 0x6c, 0xd2,
	0xd0, 0x0e, 0x61, 0x62, 0xb7, 0x1d, 0x76, 0x58, 0x7b, 0xa8, 0x84, 0x8a, 0x2a, 0x17, 0xb5, 0x12,
	0x3d, 0x44, 0x26, 0x71, 0x49, 0xa4, 0x90, 0x44, 0xb1, 0x45, 0xe9, 0x07, 0xe8, 0xb9, 0xbd, 0xf5,
	0xdc, 0x6f, 0x5a, 0x61, 0x87, 0x90, 0x84, 0xfe, 0x3b, 0xf4, 0x12, 0xc5, 0xef, 0xfb, 0xbc, 0x79,
	0x7e, 0xf6, 0x13, 0x83, 0x19, 0x30, 0x77, 0xce, 0x92, 0x41, 0x72, 0xc1, 0x99, 0x50, 0x4f, 0x2b,
	0x4e, 0x22, 0x11, 0xe1, 0x9a, 0x5c, 0xf4, 0x6e, 0x11, 0x18, 0x93, 0x15, 0x61, 0xd4, 0x3d, 0x4d,
	0x7c, 0xc1, 0x8e, 0x99, 0xc0, 0xff, 0x00, 0x5c, 0x2a, 0xa8, 0xbd, 0x88, 0x5c, 0x16, 0x98, 0xa8,
	0x8b, 0xfa, 0xc6, 0xf0, 0xab, 0xa5, 0x66, 0x8b, 0x52, 0x6b, 0x9f, 0x0a, 0x7a, 0xb8, 0x96, 0x11,
	0xcd, 0xdd, 0xbc, 0xe2, 0xdf, 0xf0, 0x2e, 0xe4, 0xb6, 0xd4, 0x9b, 0x95, 0x6e, 0xb5, 0xdf, 0x18,
	0xb6, 0xd3, 0xe9, 0x31, 0xcf, 0x4f, 0x93, 0xb7, 0x21, 0x27, 0x12, 0xe2, 0x23, 0x68, 0xd9, 0x97,
	0x70, 0x1d, 0x2a, 0xa3, 0x93, 0x0f, 0x6f, 0x7a, 0x77, 0x08, 0x8c, 0xe2, 0x00, 0xee, 0x80, 0x16,
	0xd2, 0x05, 0xe3, 0x31, 0x75, 0x98, 0x04, 0xd3, 0xc8, 0xb6, 0x80, 0x5b, 0x50, 0xdb, 0x98, 0xa2,
	0xbe, 0x4e, 0xd4, 0x02, 0x9f, 0xc1, 0x27, 0x27, 0x0a, 0x02, 0xe6, 0x08, 0x3f, 0x0a, 0x6d, 0x8f,
	0x72, 0x8f, 0xb9, 0x29, 0x5c, 0x55, 0xc2, 0x7d, 0x4f, 0xe1, 0xf6, 0x32, 0xd5, 0x81, 0x14, 0x15,
	0x50, 0xdb, 0x4e, 0xb9, 0x2b, 0xc1, 0x6f, 0x10, 0x74, 0x9e, 0x9a, 0xc3, 0x3f, 0xe1, 0x7d, 0xce,
	0x7d, 0xcd, 0x9a, 0x72, 0x1b, 0xdb, 0xf2, 0x98, 0x2e, 0x18, 0xfe, 0x06, 0x7a, 0x81, 0x4d, 0xed,
	0xa1, 0xe1, 0x6d, 0xcd, 0xf0, 0x0f, 0x30, 0xe2, 0xa5, 0x50, 0x7d, 0xb9, 0x11, 0xb3, 0x2a, 0x45,
	0x7a, 0xbc, 0x14, 0x52, 0xb1, 0xf6, 0xef, 0x5d, 0x23, 0x68, 0x4e, 0x56, 0x47, 0x4b, 0xf1, 0xaa,
	0x99, 0xfe, 0x05, 0x3d, 0xe4, 0x76, 0x66, 0x9f, 0xe6, 0x6a, 0x66, 0xb9, 0x96, 0xfc, 0x08, 0x84,
	0xb2, 0x24, 0x0f, 0xe9, 0x0a, 0x41, 0x73, 0x47, 0xf1, 0x4c, 0x96, 0x04, 0x5a, 0xb9, 0x73, 0x2b,
	0xfb, 0x76, 0x77, 0x22, 0x2b, 0xfb, 0x63, 0xa7, 0xd0, 0x92, 0x1c, 0x53, 0xf8, 0xfc, 0xe8, 0xc0,
	0xcb, 0x83, 0x7a, 0xf0, 0x2f, 0xfb, 0x3f, 0x82, 0x5f, 0x51, 0x32, 0xb7, 0xbc, 0xcb, 0x98, 0x25,
	0xea, 0xca, 0x59, 0xe7, 0x74, 0x96, 0xf8, 0x8e, 0xba, 0x6d, 0xdc, 0x4a, 0x8b, 0x52, 0x3d, 0xfd,
	0xe2, 0x32, 0x16, 0x3b, 0x1e, 0xf5, 0xc3, 0x81, 0x6a, 0x0f, 0xf2, 0xd7, 0x74, 0x56, 0x97, 0xc5,
	0x3f, 0xf7, 0x01, 0x00, 0x00, 0xff, 0xff, 0x54, 0x68, 0x0d, 0xd5, 0xbd, 0x03, 0x00, 0x00,
}
