// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package msgs // import "deepchain/core/ledger/kvledger/txmgmt/statedb/stateleveldb/msgs"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VersionedValueProto struct {
	VersionBytes         []byte   `protobuf:"bytes,1,opt,name=version_bytes,json=versionBytes,proto3" json:"version_bytes,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Metadata             []byte   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionedValueProto) Reset()         { *m = VersionedValueProto{} }
func (m *VersionedValueProto) String() string { return proto.CompactTextString(m) }
func (*VersionedValueProto) ProtoMessage()    {}
func (*VersionedValueProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_1c711b1521b818b4, []int{0}
}
func (m *VersionedValueProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionedValueProto.Unmarshal(m, b)
}
func (m *VersionedValueProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionedValueProto.Marshal(b, m, deterministic)
}
func (dst *VersionedValueProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionedValueProto.Merge(dst, src)
}
func (m *VersionedValueProto) XXX_Size() int {
	return xxx_messageInfo_VersionedValueProto.Size(m)
}
func (m *VersionedValueProto) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionedValueProto.DiscardUnknown(m)
}

var xxx_messageInfo_VersionedValueProto proto.InternalMessageInfo

func (m *VersionedValueProto) GetVersionBytes() []byte {
	if m != nil {
		return m.VersionBytes
	}
	return nil
}

func (m *VersionedValueProto) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *VersionedValueProto) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionedValueProto)(nil), "msgs.VersionedValueProto")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_storage_1c711b1521b818b4) }

var fileDescriptor_storage_1c711b1521b818b4 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0xbd, 0x0a, 0xc2, 0x30,
	0x14, 0x85, 0xa9, 0x7f, 0x48, 0x68, 0x97, 0xea, 0x50, 0x9c, 0x44, 0x17, 0x27, 0x33, 0xf8, 0x00,
	0x62, 0x9f, 0x40, 0x1c, 0x3a, 0xb8, 0xc8, 0x4d, 0x73, 0x89, 0xc5, 0xa4, 0x29, 0xc9, 0x35, 0xe8,
	0xdb, 0x4b, 0xd3, 0xe2, 0x74, 0xef, 0xf9, 0x3e, 0x0e, 0x1c, 0x96, 0x79, 0xb2, 0x0e, 0x14, 0x1e,
	0x3b, 0x67, 0xc9, 0xe6, 0x33, 0xe3, 0x95, 0xdf, 0x69, 0xb6, 0xaa, 0xd0, 0xf9, 0xc6, 0xb6, 0x28,
	0x2b, 0xd0, 0x6f, 0xbc, 0x46, 0xb9, 0x67, 0x59, 0x18, 0xf0, 0x43, 0x7c, 0x09, 0x7d, 0x91, 0x6c,
	0x93, 0x43, 0x7a, 0x4b, 0x47, 0x58, 0xf6, 0x2c, 0x5f, 0xb3, 0x79, 0xe8, 0x2b, 0xc5, 0x24, 0xca,
	0x21, 0xe4, 0x1b, 0xb6, 0x34, 0x48, 0x20, 0x81, 0xa0, 0x98, 0x46, 0xf1, 0xcf, 0xe5, 0xe5, 0x7e,
	0x96, 0x88, 0x5d, 0xfd, 0x84, 0xa6, 0xe5, 0xb5, 0x75, 0xc8, 0x35, 0x4a, 0x85, 0x8e, 0xbf, 0xc2,
	0xf8, 0xd0, 0xc7, 0x28, 0x43, 0xdc, 0x13, 0x10, 0x4a, 0x31, 0x5c, 0x8d, 0x01, 0xb5, 0x14, 0xbc,
	0x1f, 0x2c, 0x16, 0x71, 0xfd, 0xe9, 0x17, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x2b, 0x8e, 0xd1, 0xce,
	0x00, 0x00, 0x00,
}
