// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pvtdata_key.proto

package pvtstatepurgemgmt // import "deepchain/core/ledger/kvledger/txmgmt/pvtstatepurgemgmt"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PvtdataKeys struct {
	Map                  map[string]*Collections `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PvtdataKeys) Reset()         { *m = PvtdataKeys{} }
func (m *PvtdataKeys) String() string { return proto.CompactTextString(m) }
func (*PvtdataKeys) ProtoMessage()    {}
func (*PvtdataKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_pvtdata_key_74505827c413d764, []int{0}
}
func (m *PvtdataKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PvtdataKeys.Unmarshal(m, b)
}
func (m *PvtdataKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PvtdataKeys.Marshal(b, m, deterministic)
}
func (dst *PvtdataKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PvtdataKeys.Merge(dst, src)
}
func (m *PvtdataKeys) XXX_Size() int {
	return xxx_messageInfo_PvtdataKeys.Size(m)
}
func (m *PvtdataKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_PvtdataKeys.DiscardUnknown(m)
}

var xxx_messageInfo_PvtdataKeys proto.InternalMessageInfo

func (m *PvtdataKeys) GetMap() map[string]*Collections {
	if m != nil {
		return m.Map
	}
	return nil
}

type Collections struct {
	Map                  map[string]*KeysAndHashes `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Collections) Reset()         { *m = Collections{} }
func (m *Collections) String() string { return proto.CompactTextString(m) }
func (*Collections) ProtoMessage()    {}
func (*Collections) Descriptor() ([]byte, []int) {
	return fileDescriptor_pvtdata_key_74505827c413d764, []int{1}
}
func (m *Collections) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collections.Unmarshal(m, b)
}
func (m *Collections) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collections.Marshal(b, m, deterministic)
}
func (dst *Collections) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collections.Merge(dst, src)
}
func (m *Collections) XXX_Size() int {
	return xxx_messageInfo_Collections.Size(m)
}
func (m *Collections) XXX_DiscardUnknown() {
	xxx_messageInfo_Collections.DiscardUnknown(m)
}

var xxx_messageInfo_Collections proto.InternalMessageInfo

func (m *Collections) GetMap() map[string]*KeysAndHashes {
	if m != nil {
		return m.Map
	}
	return nil
}

type KeysAndHashes struct {
	List                 []*KeyAndHash `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *KeysAndHashes) Reset()         { *m = KeysAndHashes{} }
func (m *KeysAndHashes) String() string { return proto.CompactTextString(m) }
func (*KeysAndHashes) ProtoMessage()    {}
func (*KeysAndHashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_pvtdata_key_74505827c413d764, []int{2}
}
func (m *KeysAndHashes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeysAndHashes.Unmarshal(m, b)
}
func (m *KeysAndHashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeysAndHashes.Marshal(b, m, deterministic)
}
func (dst *KeysAndHashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeysAndHashes.Merge(dst, src)
}
func (m *KeysAndHashes) XXX_Size() int {
	return xxx_messageInfo_KeysAndHashes.Size(m)
}
func (m *KeysAndHashes) XXX_DiscardUnknown() {
	xxx_messageInfo_KeysAndHashes.DiscardUnknown(m)
}

var xxx_messageInfo_KeysAndHashes proto.InternalMessageInfo

func (m *KeysAndHashes) GetList() []*KeyAndHash {
	if m != nil {
		return m.List
	}
	return nil
}

type KeyAndHash struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyAndHash) Reset()         { *m = KeyAndHash{} }
func (m *KeyAndHash) String() string { return proto.CompactTextString(m) }
func (*KeyAndHash) ProtoMessage()    {}
func (*KeyAndHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_pvtdata_key_74505827c413d764, []int{3}
}
func (m *KeyAndHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyAndHash.Unmarshal(m, b)
}
func (m *KeyAndHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyAndHash.Marshal(b, m, deterministic)
}
func (dst *KeyAndHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyAndHash.Merge(dst, src)
}
func (m *KeyAndHash) XXX_Size() int {
	return xxx_messageInfo_KeyAndHash.Size(m)
}
func (m *KeyAndHash) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyAndHash.DiscardUnknown(m)
}

var xxx_messageInfo_KeyAndHash proto.InternalMessageInfo

func (m *KeyAndHash) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyAndHash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func init() {
	proto.RegisterType((*PvtdataKeys)(nil), "pvtstatepurgemgmt.PvtdataKeys")
	proto.RegisterMapType((map[string]*Collections)(nil), "pvtstatepurgemgmt.PvtdataKeys.MapEntry")
	proto.RegisterType((*Collections)(nil), "pvtstatepurgemgmt.Collections")
	proto.RegisterMapType((map[string]*KeysAndHashes)(nil), "pvtstatepurgemgmt.Collections.MapEntry")
	proto.RegisterType((*KeysAndHashes)(nil), "pvtstatepurgemgmt.KeysAndHashes")
	proto.RegisterType((*KeyAndHash)(nil), "pvtstatepurgemgmt.KeyAndHash")
}

func init() { proto.RegisterFile("pvtdata_key.proto", fileDescriptor_pvtdata_key_74505827c413d764) }

var fileDescriptor_pvtdata_key_74505827c413d764 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4b, 0x84, 0x50,
	0x10, 0xc7, 0x79, 0xbb, 0x5b, 0xd4, 0x58, 0x50, 0xef, 0x24, 0x41, 0x21, 0x5e, 0xf2, 0xa4, 0x64,
	0x51, 0x6d, 0xb7, 0x36, 0x82, 0x20, 0x82, 0xf0, 0x10, 0xd1, 0x25, 0x5e, 0x3a, 0xa8, 0xf8, 0xeb,
	0xe1, 0x9b, 0x95, 0xfc, 0x6f, 0xa2, 0xbf, 0x34, 0x74, 0x8d, 0xb4, 0x95, 0xba, 0x0d, 0x33, 0x9f,
	0xf9, 0xce, 0xe7, 0xc1, 0x83, 0x7d, 0x59, 0x51, 0x20, 0x48, 0xbc, 0x26, 0x58, 0xdb, 0xb2, 0x2c,
	0xa8, 0xe0, 0x4d, 0x4b, 0x91, 0x20, 0x94, 0xcb, 0x32, 0xc4, 0x2c, 0xcc, 0xc8, 0xfc, 0x60, 0xa0,
	0x3d, 0xae, 0xc0, 0x7b, 0xac, 0x15, 0x9f, 0xc3, 0x34, 0x13, 0x52, 0x67, 0xc6, 0xd4, 0xd2, 0xdc,
	0x63, 0x7b, 0x6d, 0xc1, 0xee, 0xc1, 0xf6, 0x83, 0x90, 0xb7, 0x39, 0x95, 0xb5, 0xd7, 0xec, 0x1c,
	0x3c, 0xc1, 0xd6, 0x77, 0x83, 0xef, 0xc1, 0x34, 0xc1, 0x5a, 0x67, 0x06, 0xb3, 0xb6, 0xbd, 0xa6,
	0xe4, 0x67, 0xb0, 0x51, 0x89, 0x74, 0x89, 0xfa, 0xc4, 0x60, 0x96, 0xe6, 0x1e, 0x8d, 0x44, 0xdf,
	0x14, 0x69, 0x8a, 0x3e, 0xc5, 0x45, 0xae, 0xbc, 0x15, 0x7c, 0x35, 0xb9, 0x64, 0xe6, 0x27, 0x03,
	0xad, 0x37, 0xfa, 0x5f, 0xb1, 0x07, 0xff, 0x52, 0x7c, 0xfe, 0x53, 0xf1, 0x7c, 0xa8, 0x68, 0x8c,
	0x44, 0x37, 0xcf, 0xbe, 0xce, 0x83, 0x3b, 0xa1, 0x22, 0x1c, 0x48, 0x2e, 0x60, 0x77, 0x30, 0xe3,
	0x27, 0x30, 0x4b, 0x63, 0x45, 0x9d, 0xe6, 0xe1, 0x78, 0x56, 0x87, 0x7b, 0x2d, 0x6a, 0xba, 0x00,
	0x3f, 0xbd, 0x11, 0x3f, 0x0e, 0xb3, 0x48, 0xa8, 0xa8, 0xd5, 0xdb, 0xf1, 0xda, 0x7a, 0x31, 0x7f,
	0xb9, 0x08, 0x10, 0xa5, 0x1f, 0x89, 0x38, 0x77, 0xfc, 0xa2, 0x44, 0x27, 0xc5, 0x20, 0xc4, 0xd2,
	0x49, 0xaa, 0xae, 0xa0, 0xf7, 0xe6, 0x9a, 0xb3, 0x76, 0xff, 0x6d, 0xb3, 0xfd, 0x14, 0xa7, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x80, 0xbf, 0x71, 0x62, 0x29, 0x02, 0x00, 0x00,
}
