// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token/expectations.proto

package token // import "deepchain/protos/token"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TokenExpectation represent the belief that someone should achieve in terms of a token action
type TokenExpectation struct {
	// Types that are valid to be assigned to Expectation:
	//	*TokenExpectation_PlainExpectation
	Expectation          isTokenExpectation_Expectation `protobuf_oneof:"Expectation"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *TokenExpectation) Reset()         { *m = TokenExpectation{} }
func (m *TokenExpectation) String() string { return proto.CompactTextString(m) }
func (*TokenExpectation) ProtoMessage()    {}
func (*TokenExpectation) Descriptor() ([]byte, []int) {
	return fileDescriptor_expectations_86284ecf0a872a1e, []int{0}
}
func (m *TokenExpectation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenExpectation.Unmarshal(m, b)
}
func (m *TokenExpectation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenExpectation.Marshal(b, m, deterministic)
}
func (dst *TokenExpectation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenExpectation.Merge(dst, src)
}
func (m *TokenExpectation) XXX_Size() int {
	return xxx_messageInfo_TokenExpectation.Size(m)
}
func (m *TokenExpectation) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenExpectation.DiscardUnknown(m)
}

var xxx_messageInfo_TokenExpectation proto.InternalMessageInfo

type isTokenExpectation_Expectation interface {
	isTokenExpectation_Expectation()
}

type TokenExpectation_PlainExpectation struct {
	PlainExpectation *PlainExpectation `protobuf:"bytes,1,opt,name=plain_expectation,json=plainExpectation,proto3,oneof"`
}

func (*TokenExpectation_PlainExpectation) isTokenExpectation_Expectation() {}

func (m *TokenExpectation) GetExpectation() isTokenExpectation_Expectation {
	if m != nil {
		return m.Expectation
	}
	return nil
}

func (m *TokenExpectation) GetPlainExpectation() *PlainExpectation {
	if x, ok := m.GetExpectation().(*TokenExpectation_PlainExpectation); ok {
		return x.PlainExpectation
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TokenExpectation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TokenExpectation_OneofMarshaler, _TokenExpectation_OneofUnmarshaler, _TokenExpectation_OneofSizer, []interface{}{
		(*TokenExpectation_PlainExpectation)(nil),
	}
}

func _TokenExpectation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TokenExpectation)
	// Expectation
	switch x := m.Expectation.(type) {
	case *TokenExpectation_PlainExpectation:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PlainExpectation); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TokenExpectation.Expectation has unexpected type %T", x)
	}
	return nil
}

func _TokenExpectation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TokenExpectation)
	switch tag {
	case 1: // Expectation.plain_expectation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlainExpectation)
		err := b.DecodeMessage(msg)
		m.Expectation = &TokenExpectation_PlainExpectation{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TokenExpectation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TokenExpectation)
	// Expectation
	switch x := m.Expectation.(type) {
	case *TokenExpectation_PlainExpectation:
		s := proto.Size(x.PlainExpectation)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// PlainExpectation represent the plain expectation where no confidentiality is provided.
type PlainExpectation struct {
	// Types that are valid to be assigned to Payload:
	//	*PlainExpectation_ImportExpectation
	//	*PlainExpectation_TransferExpectation
	Payload              isPlainExpectation_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PlainExpectation) Reset()         { *m = PlainExpectation{} }
func (m *PlainExpectation) String() string { return proto.CompactTextString(m) }
func (*PlainExpectation) ProtoMessage()    {}
func (*PlainExpectation) Descriptor() ([]byte, []int) {
	return fileDescriptor_expectations_86284ecf0a872a1e, []int{1}
}
func (m *PlainExpectation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlainExpectation.Unmarshal(m, b)
}
func (m *PlainExpectation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlainExpectation.Marshal(b, m, deterministic)
}
func (dst *PlainExpectation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlainExpectation.Merge(dst, src)
}
func (m *PlainExpectation) XXX_Size() int {
	return xxx_messageInfo_PlainExpectation.Size(m)
}
func (m *PlainExpectation) XXX_DiscardUnknown() {
	xxx_messageInfo_PlainExpectation.DiscardUnknown(m)
}

var xxx_messageInfo_PlainExpectation proto.InternalMessageInfo

type isPlainExpectation_Payload interface {
	isPlainExpectation_Payload()
}

type PlainExpectation_ImportExpectation struct {
	ImportExpectation *PlainTokenExpectation `protobuf:"bytes,1,opt,name=import_expectation,json=importExpectation,proto3,oneof"`
}

type PlainExpectation_TransferExpectation struct {
	TransferExpectation *PlainTokenExpectation `protobuf:"bytes,2,opt,name=transfer_expectation,json=transferExpectation,proto3,oneof"`
}

func (*PlainExpectation_ImportExpectation) isPlainExpectation_Payload() {}

func (*PlainExpectation_TransferExpectation) isPlainExpectation_Payload() {}

func (m *PlainExpectation) GetPayload() isPlainExpectation_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *PlainExpectation) GetImportExpectation() *PlainTokenExpectation {
	if x, ok := m.GetPayload().(*PlainExpectation_ImportExpectation); ok {
		return x.ImportExpectation
	}
	return nil
}

func (m *PlainExpectation) GetTransferExpectation() *PlainTokenExpectation {
	if x, ok := m.GetPayload().(*PlainExpectation_TransferExpectation); ok {
		return x.TransferExpectation
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PlainExpectation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PlainExpectation_OneofMarshaler, _PlainExpectation_OneofUnmarshaler, _PlainExpectation_OneofSizer, []interface{}{
		(*PlainExpectation_ImportExpectation)(nil),
		(*PlainExpectation_TransferExpectation)(nil),
	}
}

func _PlainExpectation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PlainExpectation)
	// payload
	switch x := m.Payload.(type) {
	case *PlainExpectation_ImportExpectation:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ImportExpectation); err != nil {
			return err
		}
	case *PlainExpectation_TransferExpectation:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TransferExpectation); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PlainExpectation.Payload has unexpected type %T", x)
	}
	return nil
}

func _PlainExpectation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PlainExpectation)
	switch tag {
	case 1: // payload.import_expectation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlainTokenExpectation)
		err := b.DecodeMessage(msg)
		m.Payload = &PlainExpectation_ImportExpectation{msg}
		return true, err
	case 2: // payload.transfer_expectation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlainTokenExpectation)
		err := b.DecodeMessage(msg)
		m.Payload = &PlainExpectation_TransferExpectation{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PlainExpectation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PlainExpectation)
	// payload
	switch x := m.Payload.(type) {
	case *PlainExpectation_ImportExpectation:
		s := proto.Size(x.ImportExpectation)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PlainExpectation_TransferExpectation:
		s := proto.Size(x.TransferExpectation)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// PlainTokenExpectation represents the expecation that
// certain outputs will be matched
type PlainTokenExpectation struct {
	// Outputs contains the expected outputs
	Outputs              []*PlainOutput `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PlainTokenExpectation) Reset()         { *m = PlainTokenExpectation{} }
func (m *PlainTokenExpectation) String() string { return proto.CompactTextString(m) }
func (*PlainTokenExpectation) ProtoMessage()    {}
func (*PlainTokenExpectation) Descriptor() ([]byte, []int) {
	return fileDescriptor_expectations_86284ecf0a872a1e, []int{2}
}
func (m *PlainTokenExpectation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlainTokenExpectation.Unmarshal(m, b)
}
func (m *PlainTokenExpectation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlainTokenExpectation.Marshal(b, m, deterministic)
}
func (dst *PlainTokenExpectation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlainTokenExpectation.Merge(dst, src)
}
func (m *PlainTokenExpectation) XXX_Size() int {
	return xxx_messageInfo_PlainTokenExpectation.Size(m)
}
func (m *PlainTokenExpectation) XXX_DiscardUnknown() {
	xxx_messageInfo_PlainTokenExpectation.DiscardUnknown(m)
}

var xxx_messageInfo_PlainTokenExpectation proto.InternalMessageInfo

func (m *PlainTokenExpectation) GetOutputs() []*PlainOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func init() {
	proto.RegisterType((*TokenExpectation)(nil), "protos.TokenExpectation")
	proto.RegisterType((*PlainExpectation)(nil), "protos.PlainExpectation")
	proto.RegisterType((*PlainTokenExpectation)(nil), "protos.PlainTokenExpectation")
}

func init() {
	proto.RegisterFile("token/expectations.proto", fileDescriptor_expectations_86284ecf0a872a1e)
}

var fileDescriptor_expectations_86284ecf0a872a1e = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x1b, 0x05, 0x8b, 0x13, 0x85, 0x34, 0xfe, 0x0b, 0x05, 0xb1, 0x44, 0x90, 0x9e, 0x12,
	0xa8, 0x67, 0x11, 0x0a, 0x62, 0x4f, 0x2a, 0xc1, 0x93, 0x17, 0xd9, 0x24, 0x93, 0x74, 0x35, 0xc9,
	0x2e, 0xbb, 0x1b, 0xb0, 0x1f, 0xcf, 0x6f, 0x26, 0xd9, 0x25, 0xb8, 0x0d, 0x3d, 0xf4, 0xb4, 0xec,
	0xcc, 0xbc, 0xdf, 0x9b, 0xe1, 0x41, 0xa0, 0xd8, 0x37, 0x36, 0x31, 0xfe, 0x70, 0xcc, 0x14, 0x51,
	0x94, 0x35, 0x32, 0xe2, 0x82, 0x29, 0xe6, 0x1f, 0xe9, 0x47, 0x4e, 0x6f, 0x4a, 0xc6, 0xca, 0x0a,
	0x63, 0xfd, 0x4d, 0xdb, 0x22, 0x56, 0xb4, 0x46, 0xa9, 0x48, 0xcd, 0xcd, 0xe0, 0xf4, 0xca, 0x20,
	0x94, 0x20, 0x8d, 0x24, 0x59, 0x87, 0x30, 0x8d, 0xf0, 0x0b, 0xbc, 0xf7, 0xae, 0xf5, 0xf4, 0x0f,
	0xf7, 0x9f, 0x61, 0xc2, 0x2b, 0x42, 0x9b, 0x4f, 0xcb, 0x31, 0x70, 0x66, 0xce, 0xdc, 0x5d, 0x04,
	0x46, 0x26, 0xa3, 0xb7, 0x6e, 0xc0, 0x12, 0xad, 0x46, 0x89, 0xc7, 0x07, 0xb5, 0xe5, 0x29, 0xb8,
	0xd6, 0x37, 0xfc, 0x75, 0xc0, 0x1b, 0xea, 0xfc, 0x17, 0xf0, 0x69, 0xcd, 0x99, 0x50, 0x3b, 0xdc,
	0xae, 0xb7, 0xdc, 0x86, 0x7b, 0xae, 0x46, 0xc9, 0xc4, 0x48, 0x6d, 0x5e, 0x02, 0xe7, 0xfa, 0xca,
	0x02, 0xc5, 0x16, 0xf1, 0x60, 0x3f, 0xe2, 0x59, 0x2f, 0xb6, 0xef, 0x38, 0x86, 0x31, 0x27, 0x9b,
	0x8a, 0x91, 0x3c, 0x7c, 0x84, 0x8b, 0x9d, 0x52, 0xff, 0x0e, 0xc6, 0xac, 0x55, 0xbc, 0x55, 0x32,
	0x70, 0x66, 0x87, 0x73, 0x77, 0x71, 0x62, 0x3c, 0x5e, 0x75, 0x31, 0xe9, 0x9b, 0xcb, 0x07, 0xb8,
	0x65, 0xa2, 0x8c, 0xd6, 0x1b, 0x8e, 0xa2, 0xc2, 0xbc, 0x44, 0x11, 0x15, 0x24, 0x15, 0x34, 0xeb,
	0x37, 0xd3, 0x49, 0x7d, 0x5c, 0xe6, 0x88, 0x3c, 0x5b, 0x13, 0xda, 0x98, 0x50, 0x65, 0xac, 0xeb,
	0xa9, 0x49, 0xfc, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xb2, 0x5c, 0xbb, 0x14, 0x02, 0x00,
	0x00,
}
